#!/usr/bin/env bash

shopt -s globstar dotglob nullglob

function help {
	local command_name

	command_name="$(basename "$0")"
	echo "${command_name} - recursively synchronizes the default branch for one or more git repositories"
	echo -e "\nUsage: ${command_name} [<directory-path>"]
	echo -e "\nOptions:"
	echo -e "\t-h, --help\tprints help"
	echo -e "\t-v, --version\tprints version"
	exit 0
}

function version {
	local command_name
	local version

	command_name="$(basename "$0")"
	version="1.1.0"

	echo "${command_name} - ${version}"
	exit 0
}

# usually the default branch name is either "master" or "main"
function get_default_branch_name {
	git rev-parse --abbrev-ref origin/HEAD | cut -c8-
}

function is_repo_dirty {
	[[ $(git status -s | wc -l) -gt 0 ]]
}

function get_total_remotes {
	git remote 2>/dev/null | wc -l
}

function has_exactly_1_remote {
	local total_remotes

	total_remotes=$(get_total_remotes)
	[[ "${total_remotes}" -eq 1 ]]
}

function sync {
	local default_branch
	local original_branch

	default_branch="${1}"
	original_branch=$(git branch --show-current)

	git switch "${default_branch}" &>/dev/null # usually, master or main
	hash_before_sync=$(git rev-parse HEAD)

	git pull "$(git remote)" "${default_branch}" &>/dev/null
	hash_after_sync=$(git rev-parse HEAD)

	git switch "${original_branch}" &>/dev/null # go back to the original branch

	if [[ "${hash_before_sync}" != "${hash_after_sync}" ]]; then
		project_updated=true
	fi
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
	help
fi

if [[ "$1" == "--version" || "$1" == "-v" ]]; then
	version
fi

############ colors ################
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
NOCOLOR='\033[0m'
####################################

project_updated=false # indicates whether the git repository had or not changes since the last sync

path="${1:-.}" # uses the current working directory by default when no argument is given
if [[ ! -d "${path}" || ! -r "${path}" ]]; then
	echo -e "${RED}error: '${path}' not found or is unreadable or is not a directory.${NOCOLOR}" >&2
	exit 1
fi

repositories=("${path}"/**/.git/)

if [[ "${#repositories[@]}" -eq 0 ]]; then
	echo -e "${RED}error: no .git directories found in '${path}'${NOCOLOR}"
	exit 1
fi

for repository in "${repositories[@]}"; do
	project=$(dirname "${repository}")
	(
		cd "${project}" || help
		if ! has_exactly_1_remote; then
			echo -e "${RED}error: skipping '${project}' - must have exactly 1 remote configured, but $(get_total_remotes) found.${NOCOLOR}" >&2
		else
			if is_repo_dirty; then
				echo -e "${RED}error: skipping '${project}' because it is dirty.${NOCOLOR}" >&2
			else
				branch=$(get_default_branch_name)
				echo -n "syncing '${project}' ('${branch}' branch)... "
				if ! sync "${branch}" &>/dev/null; then
					echo -e "${RED}failed.${NOCOLOR}" >&2
				else
					if "${project_updated}"; then
						echo -e "${BLUE}done!${NOCOLOR} ${GREEN}(updated)${NOCOLOR}"
					else
						echo -e "${BLUE}done!${NOCOLOR} ${ORANGE}(no changes)${NOCOLOR}"
					fi
				fi
			fi
		fi
	)
done
